export type RegulationTemplateType = "CORRIDA_RUA" | "TRAIL_RUN" | "CORRIDA_KIDS";

export type RegulationConfigDto = {
  id: string;
  eventId: string;
  templateTipo: RegulationTemplateType;
  possuiKids: boolean;
  possuiChip: boolean;
  possuiPremiacaoDinheiro: boolean;
  permiteTransferencia: boolean;
  permiteRetiradaTerceiros: boolean;
  exigeAtestadoMedico: boolean;
  logoDataUrl: string | null;
  faixaEtariaInicio: number;
  faixaEtariaFim: number;
  intervaloFaixaEtaria: number;
  tempoLimiteMinutos: number;
  plataformaInscricao: string[];
  valorInscricao: string;
  limiteVagas: number;
  kitDescricao: string | null;
  premiacaoDescricao: string | null;
  regrasGeraisExtra: string | null;
  documentosObrigatorios: string | null;
  politicaCancelamento: string | null;
  emailContato: string;
  whatsappContato: string;
  dataInicioInscricao: string;
  dataFimInscricao: string;
  criadoEm: string;
  atualizadoEm: string;
};

export type RegulationEventDto = {
  id: string;
  nomeEvento: string;
  dataEvento: string;
  cidade: string;
  estado: string;
  localLargada: string;
  organizador: string;
};

export type RegulationConfigInput = {
  eventId: string;
  templateTipo: RegulationTemplateType;
  possuiKids: boolean;
  possuiChip: boolean;
  possuiPremiacaoDinheiro: boolean;
  permiteTransferencia: boolean;
  permiteRetiradaTerceiros: boolean;
  exigeAtestadoMedico: boolean;
  logoDataUrl?: string | null;
  faixaEtariaInicio: number;
  faixaEtariaFim: number;
  intervaloFaixaEtaria: number;
  tempoLimiteMinutos: number;
  plataformaInscricao: string[];
  valorInscricao: number;
  limiteVagas: number;
  kitDescricao?: string | null;
  premiacaoDescricao?: string | null;
  regrasGeraisExtra?: string | null;
  documentosObrigatorios?: string | null;
  politicaCancelamento?: string | null;
  emailContato: string;
  whatsappContato: string;
  dataInicioInscricao: string;
  dataFimInscricao: string;
};
